services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PORT
        value: "10000"
